---
commonLabels:
  app.kubernetes.io/name: alb-ingress-controller

imageTags:
  - name: docker.io/amazon/aws-alb-ingress-controller
    newTag: v1.1.5

namespace: kube-system

resources:
  - alb-ingress-controller.yaml
  - rbac-role.yaml
