apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  config.toml: |
    [foo]
    bar = "hello"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debugkit
  name: debugkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugkit
  template:
    metadata:
      labels:
        app: debugkit
    spec:
      containers:
        - image: amaya382/k8s-debugkit
          name: k8s-debugkit
          volumeMounts:
            - name: config-files
              mountPath: /etc/config
          env:
            - name: MY_ENV
              value: cool!
      volumes:
        - name: config-files
          configMap:
            name: my-config
