---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:node-proxier
      rolearn: arn:aws:iam::XXXXXXXXXXX:role/eksctl-demo-cluster-FargatePodExecutionRole-11QMH29B342II
      username: system:node:{{SessionName}}
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::XXXXXXXXXXX:user/user-a
      username: user-a
