---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alb-ingress-controller
spec:
  template:
    spec:
      containers:
        - name: alb-ingress-controller
          args:
            - --ingress-class=alb
            - --cluster-name=demo
            - --aws-vpc-id=vpc-0761f631f4255b206
            - --aws-region=ap-northeast-1
