apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sample-role
  namespace: default
rules:
  - apiGroups:
      - apps
      - extentions
    resources:
      - replicasets
      - deployments
      - deployments/scale
    verbs:
      - "*"