---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-container
          image: nginx:1.12
          imagePullPolicy: Always
          ports:
            - containerPort: 80
