---
bases:
  - ../bases/aws-auth
  - ../bases/aws-alb-ingress-controller
patchesStrategicMerge:
  - patch/patch-aws-auth.yaml
  - patch/patch-aws-alb-ingress-controller.yaml
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
