---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: eks/argocd/manifest/overlays/dev/ap-northeast-1/default
    repoURL: 'https://github.com/mfykmn/cncf.git'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
