apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-branch=master
            - --git-path=staging
            - --git-user=mafuyuk
            - --git-email=mafuyuk.m@gmail.com
            - --git-url=git@github.com:mfykmn/demo-k8s-manifest
