apiVersion: v1
kind: Pod
metadata:
  name: sample-secret-multi-env
spec:
  containers:
    - name: secret-container
      image: nginx:1.12
      envFrom:
        - secretKeyRef:
            name: sample-db-auth
          prefix: DB1_
        - secretKeyRef:
            name: sample-db-auth
          prefix: DB2_